apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: workshop
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  DATABASE_NAME: d29ya3Nob3BfZGV2ZWxvcG1lbnQ=
