apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: workshop
type: Opaque
data:
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  DATABASE_NAME: "${DATABASE_NAME}"
